### ISSUE TITLE
Connector not working

### ISSUE THREAD

**Issue by jerome42** [konnectors/cozy-konnector-bank-cragr#90]
The Credit Agricole Paris Ile de France have changed :
Old URL : www.ca-paris.fr
New URL : www.credit-agricole.fr/ca-paris/
The connexion method have changed ...
All The Credit Agricole Caisses Régionales sites are going to change in 2019
... so this connector is no longer working

**Comment by rclement** [comment]
I just checked on my cozy.io instance this morning, everything seems to be properly synchronized even though the connection URL has changed.
